---

- name: pull-configure | Ensure for the pull user exists
  user: name={{pull_user}} createhome=yes

- name: pull-configure | Setup fingerprints
  lineinfile: >
    line="{{item}}"
    dest="{{pull_user_ssh_home}}/known_hosts"
    insertafter="EOF"
    state="present"
    create="yes"
    owner="{{pull_user}}"
    group="{{pull_group}}"
    mode="0644"
  with_items: "{{pull_fingerprints}}"

- name: pull-configure | Copy private keys
  copy: src={{item}} dest={{pull_user_ssh_home}}/{{item|basename}} owner={{pull_user}} group={{pull_group}} mode=0400
  with_items: "{{pull_ssh_keys_copy}}"

- name: pull-configure | Copy private keys
  file:
    content: "{{item.value}}"
    dest: "{{pull_user_ssh_home}}/{{item.key}}"
    owner: "{{pull_user}}"
    group: "{{pull_group}}"
    mode: 0400
  with_dict: "{{pull_ssh_keys}}"

- name: pull-configure | Create pull directories
  file: state=directory owner={{pull_user}} group={{pull_group}} path={{item}} recurse=yes
  with_items:
  - "{{pull_logdir}}"
  - "{{pull_workdir}}"

- name: pull-configure | Configure inventory file
  template: src=inventory.ini.j2 dest={{pull_workdir}}/{{item.name}}.ini owner={{pull_user}} group={{pull_group}} mode=0644
  with_items: "{{pull_sources}}"

- name: pull-configure | Configure vars
  template: src=pull.json.j2 dest={{pull_workdir}}/{{item.name}}.json owner={{pull_user}} group={{pull_group}} mode=0755
  with_items: "{{pull_sources}}"

- name: pull-configure | Configure runscript
  template: src=pull.sh.j2 dest={{pull_workdir}}/pull.sh owner={{pull_user}} group={{pull_group}} mode=0755

- name: pull-configure | Configure cron
  template: src=cron.j2 dest=/etc/cron.d/ansible-pull owner=root group=root mode=0644

- name: pull-configure | Configure logrotate
  template: src=logrotate.j2 dest=/etc/logrotate.d/ansible-pull owner=root group=root mode=0644
