---

- name: pull-install | Install requirements
  apt: name={{item}}
  with_items: [cron, logrotate, python-software-properties]

- name: pull-install | Add ansible ppa
  apt_repository: repo={{pull_ansible_ppa}} update_cache=yes

- name: pull-install | Install ansible
  apt: name=ansible

- name: pull-install | Install mailutils
  apt: name=mailutils
  when: pull_mail_to != ""
